# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            GreenBot
tagline:          'The Open Source Bot Server'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://green-bot.github.io.git
baseurl:          /

author:
  name:           'Thomas Howe'
  url:            https://twitter.com/howethomas

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/green-bot/greenbot-core
